# Before Script
before_script:
  - echo "memory_limit = 256M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/ci-runner.ini
  - composer self-update
  - composer install --prefer-dist > /dev/null

php:7.0:
  image: bobey/docker-gitlab-ci-runner-php7
  script:
    - echo "Running PHPUnit Tests"
    - php vendor/bin/phpunit --colors